name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Coverage
        working-directory: ./frontend
        run: npm run coverage

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Coverage
        working-directory: ./backend
        run: npm run coverage
