info:
  name: Get Subtasks
  type: http
  seq: 1

http:
  method: GET
  url: http://localhost:5000/api/tasks/101/subtasks
  body:
    type: json
    data: ""
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
