info:
  name: Reject Task
  type: http
  seq: 6

http:
  method: POST
  url: http://localhost:5000/api/tasks/101/reject
  body:
    type: json
    data: |-
      {
        "comment": "Needs more work."
      }
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
