info:
  name: Update Task Status
  type: http
  seq: 4

http:
  method: PATCH
  url: http://localhost:5000/api/tasks/101/status
  body:
    type: json
    data: |-
      {
        "status": "in_review"
      }
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
