info:
  name: Upload Task Image
  type: http
  seq: 8

http:
  method: POST
  url: http://localhost:5000/api/tasks/101/image
  body:
    type: multipartForm
    multipartForm:
      - name: image
        value: "@file()"
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
